language: go

go:
  - 1.12.x
  - tip

before_install:
  - cd dob-api && go get -t -v ./...

before_script:
  - cd dob-api

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
